### ISSUE TITLE
slave not promoted to master when master is down

### ISSUE THREAD

**Issue by kahidna** [mhagander/bgw_replstatus#2]
hi everyone.
I try to implement PostgreSQL high availability using __bgw_replstatus__ and __haproxy__. 
according to part of your readme, it said :
> automatically switches over to the backup node if the master goes down and the backup is promoted.

but I have an issue when the master instance is down, the slave does not take over/ promoted to master node. here is my environment :

1. dockerized PostgreSQL 9.68 
2. installed bgw_replstatus version 1.02 inside the container fetch from ![here](https://www.ubuntuupdates.org/package/postgresql/trusty-pgdg/main/base/postgresql-9.6-bgw-replstatus)
3. haproxy 1.7.11-1

here is my __postgresql.conf__ configuration on _master_ node that I change : 
````
wal_level = hot_standby
archive_mode = on
archive_command = 'test ! -f mnt/server/archivedir/%f && cp %p mnt/server/archivedir/%f'
max_wal_senders = 3
wal_keep_segments = 1000
shared_preload_libraries = 'bgw_replstatus'
````
here is my __postgresql.conf__ on _slave_ node after `pg_basebackup`  which I change:
```
hot_standby = on
```
and here is my __recovery.conf__ on the _slave_ node
```
standby_mode = on
primary_conninfo = 'host=[host-ip-source] port=[source-port] user=repuser password=[some-password]'
```

and here is my haproxy configuration
```
frontend pgcluster
	bind *:5433
	mode tcp
	default_backend pgcluster

backend pgcluster
	mode tcp
	balance roundrobin
	option tcp-check
	tcp-check expect string MASTER
	server tm 172.31.32.129:5444 check port 5446
        server x2 172.31.18.158:5554 check port 5400 backup
```
here is the return when I test it using `nc [ip-address] [port-bgw_replstatus]` command
![image](https://user-images.githubusercontent.com/4997301/40159950-b95de288-59d5-11e8-85c2-6829a4960856.png)

when all node is up, the PostgreSQL running well, and I can access it using this command :     
`psql -h some.domain.to.pgcluster -p 5433 -U postgres`
&nbsp;
![image](https://user-images.githubusercontent.com/4997301/40160727-b391234e-59d8-11e8-99e3-f508ee678595.png)

but when the master is down, the slave is not promoted to master/not takeover here is the return :   
![image](https://user-images.githubusercontent.com/4997301/40160980-8ad693d4-59d9-11e8-8e4c-efc90c20ef0a.png)

is there a miss configuration or is there workaround which I can use to implement this high availability for haproxy?

**Comment by df7cb** [comment]
Hi,
neither bgw_replstatus nor haproxy do the actual failover, i.e. they do not promote a standby server to be the new primary. If you want that, you need to use pacemaker, patroni, or repmgr.
